// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spprszcqhfkwjsijdept.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwcHJzemNxaGZrd2pzaWpkZXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODgzODIsImV4cCI6MjA3MDE2NDM4Mn0.8tYXNW76PZOmz3BD4QzdSSJebb3ZzNjRbh1IIxDF47o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});